<StreamScreen>:
    FloatLayout:
        id: main_layout
        BoxLayout:
            pos_hint: {"x": .05, "top":.95}
            size_hint: (.9, .8)
            id: stream_box
        BoxLayout:
            pos_hint: {"right": .95, "top":.95}
            size_hint: (.3, .3)
            id: camera_box
        BoxLayout:
            pos_hint: {"x": .1, "top":.15}
            size_hint: (.8, .1)
            id: buttons_box